### ISSUE TITLE
pogo pins and magnets

### ISSUE THREAD

**Issue by kriku** [Szybet/Yatchy#4]
hi! great work! looks amazing!

I have a suggestion

how do you think, is it possible to move type-c connector to other part, like rp2040-tiny https://www.waveshare.com/wiki/RP2040-Tiny.

I mean you don't have to update firmware frequently, and if you move out type-c circuit - it will safe a lot of space and overall thickness will be thinner. 

and make pogo pins for charging

what do you think?

**Comment by Szybet** [comment]
First, many people suggested pogo pins, the answer is one:
# No, kind of
And the big no is there for a reason. I had many devices using pogo pins, in all of them the pogo pins broke. Lenovo tablet, xiaomi smartwatch and countless others. It's a flawed technology. Even in new premium devices, I had enough of reddit post about the framework laptop "the keyboard module doesn't work" "try to reattach it, it was the pogo pins" - And it's only now, let's wait until they wear out and stop fully working, like they did for my devices.
Why kind of? because you can simply not solder the USBC connector to the board (saving on thickness) and just expose pogo pin pads outside the case & wires to the default module or just create a dedicated module for pogo pins, to charge it from there. 5V is exposed there, no issue in that:
![image](https://github.com/user-attachments/assets/ef6f7b40-d36c-49e0-84f1-c263eeb9c681)
Oh also USB-C is for charging too ;p
